// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CheckUserNameReq struct {
	UserName string `json:"userName"`
}

type CheckUserNameResp struct {
	Code string `json:"code"`
}

type DeleteUserReq struct {
	UserID int64 `json:"user_id"`
}

type DeleteUserResp struct {
	Code string `json:"code"`
}

type GetUserDetailReq struct {
	UserID int64 `json:"user_id"`
}

type GetUserDetailResp struct {
	Code        string `json:"code"`
	UserID      int64  `json:"userId,omitempty"`
	UserName    string `json:"userName,omitempty"`
	PhoneNumber string `json:"userPhoneNumber,omitempty"`
}

type IsManagerReq struct {
	UserID int64 `json:"user_id"`
}

type IsManagerResp struct {
	Code      string `json:"code"`
	IsManager bool   `json:"isManager"`
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code     string `json:"code"`
	UserID   int64  `json:"userId,omitempty"`
	UserName string `json:"userName,omitempty"`
	Token    string `json:"token,omitempty"`
}

type LogoutResp struct {
	Code string `json:"code"`
}

type RegisterReq struct {
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	PhoneNumber string `json:"userPhoneNumber,omitempty"`
}

type RegisterResp struct {
	Code    string `json:"code"`
	Message string `json:"message,omitempty"`
}

type UpdateUserReq struct {
	UserID      int64  `json:"user_id"`
	UserName    string `json:"userName,omitempty"`
	PhoneNumber string `json:"userPhoneNumber,omitempty"`
}

type UpdateUserResp struct {
	Code string `json:"code"`
}
