// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddCartReq struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	Num       int64 `json:"num"`
}

type AddCartResp struct {
	Code string `json:"code"`
}

type CartItem struct {
	ID          int64   `json:"id"`
	UserID      int64   `json:"user_id"`
	ProductID   int64   `json:"product_id"`
	ProductName string  `json:"productName"`
	ProductImg  string  `json:"productImg"`
	Price       float64 `json:"price"`
	Num         int64   `json:"num"`
	MaxNum      int64   `json:"maxNum"`
}

type DeleteCartReq struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

type DeleteCartResp struct {
	Code string `json:"code"`
}

type GetCartReq struct {
	UserID int64 `json:"user_id"`
}

type GetCartResp struct {
	Code  string     `json:"code"`
	Items []CartItem `json:"items,omitempty"`
}

type IsExistCartReq struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

type IsExistCartResp struct {
	Code    string `json:"code"`
	IsExist bool   `json:"isExist"`
}

type UpdateCartReq struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	Num       int64 `json:"num"`
}

type UpdateCartResp struct {
	Code string `json:"code"`
}
