// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/order/deleteOrderById",
					Handler: DeleteOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/getDetails",
					Handler: GetOrderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/order/addOrder",
					Handler: AddOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/order/getOrder",
					Handler: GetOrderHandler(serverCtx),
				},
			}...,
		),
	)
}
