// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreatePaymentReq struct {
	OrderID int64  `json:"order_id"`
	Channel string `json:"channel"`
}

type CreatePaymentResp struct {
	Code      string `json:"code"`
	PaymentNo string `json:"payment_no,omitempty"`
	PayUrl    string `json:"pay_url,omitempty"`
}

type GetPaymentStatusReq struct {
	PaymentNo string `json:"payment_no"`
}

type GetPaymentStatusResp struct {
	Code      string `json:"code"`
	PaymentNo string `json:"payment_no,omitempty"`
	OrderID   int64  `json:"order_id,omitempty"`
	Amount    int64  `json:"amount,omitempty"`
	Channel   string `json:"channel,omitempty"`
	Status    int64  `json:"status,omitempty"`
	PaidTime  int64  `json:"paid_time,omitempty"`
}

type PaymentNotifyReq struct {
	PaymentNo      string `json:"payment_no"`
	ChannelTradeNo string `json:"channel_trade_no"`
	Status         string `json:"status"`
	Amount         int64  `json:"amount"`   // 实际支付金额（分），用于校验
	PaidTime       int64  `json:"paid_time"`
	Sign           string `json:"sign"`
}

type PaymentNotifyResp struct {
	Code string `json:"code"`
}

type RefundReq struct {
	PaymentNo    string `json:"payment_no"`
	RefundAmount int64  `json:"refund_amount"`
	Reason       string `json:"reason"`
}

type RefundResp struct {
	Code     string `json:"code"`
	RefundNo string `json:"refund_no,omitempty"`
}

type GetUserPaymentsReq struct {
	UserID int64 `json:"user_id"`
}

type PaymentItem struct {
	PaymentNo string `json:"payment_no"`
	OrderID   int64  `json:"order_id"`
	Amount    int64  `json:"amount"`
	Channel   string `json:"channel"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"created_at"`
}

type GetUserPaymentsResp struct {
	Code     string        `json:"code"`
	Payments []PaymentItem `json:"payments,omitempty"`
}

type MockPayReq struct {
	PaymentNo string `json:"payment_no"`
}

type MockPayResp struct {
	Code string `json:"code"`
}
