// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type SeckillReq struct {
	ActivityID int64 `json:"activity_id"`
}

type SeckillResp struct {
	Code  string `json:"code"`
	Token string `json:"token,omitempty"`
	Msg   string `json:"msg,omitempty"`
}

type SeckillResultReq struct {
	Token string `json:"token"`
}

type SeckillResultResp struct {
	Code    string `json:"code"`
	Status  int    `json:"status"`
	OrderID int64  `json:"order_id,omitempty"`
	Msg     string `json:"msg,omitempty"`
}

type GetSeckillActivityReq struct {
	ActivityID int64 `json:"activity_id"`
}

type SeckillActivityResp struct {
	Code          string `json:"code"`
	ActivityID    int64  `json:"activity_id"`
	Title         string `json:"title"`
	ProductID     int64  `json:"product_id"`
	SeckillPrice  int64  `json:"seckill_price"`
	OriginalPrice int64  `json:"original_price"`
	Stock         int64  `json:"stock"`
	LimitPerUser  int64  `json:"limit_per_user"`
	StartTime     int64  `json:"start_time"`
	EndTime       int64  `json:"end_time"`
	Status        int    `json:"status"`
}

type ListSeckillActivitiesResp struct {
	Code       string                `json:"code"`
	Activities []SeckillActivityResp `json:"activities,omitempty"`
}

// SeckillMessage is the Kafka message payload for async order creation.
type SeckillMessage struct {
	Token        string `json:"token"`
	UserID       int64  `json:"user_id"`
	ActivityID   int64  `json:"activity_id"`
	ProductID    int64  `json:"product_id"`
	SeckillPrice int64  `json:"seckill_price"`
	Num          int64  `json:"num"`
	Timestamp    int64  `json:"timestamp"`
}
