// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users/findUserName",
				Handler: FindUserNameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/users/deleteUserById",
					Handler: DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/getDetails",
					Handler: GetUserDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/isManager",
					Handler: IsManagerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/updateUser",
					Handler: UpdateUserHandler(serverCtx),
				},
			}...,
		),
	)
}
