// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddOrderItem struct {
	ProductID    int64   `json:"product_id"`
	ProductNum   int64   `json:"product_num"`
	ProductPrice float64 `json:"product_price"`
}

type AddOrderReq struct {
	UserID int64          `json:"user_id"`
	Items  []AddOrderItem `json:"items"`
}

type AddOrderResp struct {
	Code    string `json:"code"`
	OrderID int64  `json:"order_id,omitempty"`
}

type DeleteOrderReq struct {
	OrderID int64 `json:"order_id"`
}

type DeleteOrderResp struct {
	Code string `json:"code"`
}

type GetOrderDetailReq struct {
	OrderID int64 `json:"order_id"`
}

type GetOrderDetailResp struct {
	Code   string      `json:"code"`
	Orders []OrderItem `json:"orders,omitempty"`
}

type GetOrderReq struct {
	UserID int64 `json:"user_id"`
}

type GetOrderResp struct {
	Code   string      `json:"code"`
	Orders []OrderItem `json:"orders,omitempty"`
}

type OrderItem struct {
	ID           int64   `json:"id"`
	OrderID      int64   `json:"order_id"`
	UserID       int64   `json:"user_id"`
	ProductID    int64   `json:"product_id"`
	ProductName  string  `json:"productName"`
	ProductImg   string  `json:"productImg"`
	ProductNum   int64   `json:"product_num"`
	ProductPrice float64 `json:"product_price"`
	OrderTime    string  `json:"order_time"`
	Status       int64   `json:"status"` // 0=待支付 1=已支付 2=已取消 3=已退款
}
