// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/payment/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 需要鉴权的路由
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/payment/create",
					Handler: CreatePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/payment/status",
					Handler: GetPaymentStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/payment/refund",
					Handler: RefundHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/payment/list",
					Handler: GetUserPaymentsHandler(serverCtx),
				},
			}...,
		),
	)

	// 不需要鉴权的路由（回调 + Mock）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/payment/notify",
				Handler: PaymentNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/payment/mock/pay",
				Handler: MockPayHandler(serverCtx),
			},
		},
	)
}
