// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CategoryItem struct {
	CategoryID   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
	CategoryHot  int64  `json:"category_hot"`
}

type GetAllProductResp struct {
	Code     string        `json:"code"`
	Products []ProductItem `json:"products,omitempty"`
}

type GetCategoryResp struct {
	Code       string         `json:"code"`
	Categories []CategoryItem `json:"categories,omitempty"`
}

type GetProductByCategoryReq struct {
	CategoryID int64 `json:"category_id"`
}

type GetProductByCategoryResp struct {
	Code     string        `json:"code"`
	Products []ProductItem `json:"products,omitempty"`
}

type GetProductDetailReq struct {
	ProductID int64 `json:"product_id"`
}

type GetProductDetailResp struct {
	Code    string      `json:"code"`
	Product ProductItem `json:"product,omitempty"`
}

type GetProductPicturesReq struct {
	ProductID int64 `json:"product_id"`
}

type GetProductPicturesResp struct {
	Code     string           `json:"code"`
	Pictures []ProductPicture `json:"pictures,omitempty"`
}

type GetPromoProductReq struct {
	CategoryName string `json:"category_name"`
}

type GetPromoProductResp struct {
	Code     string        `json:"code"`
	Products []ProductItem `json:"products,omitempty"`
}

type GetRecommendProductReq struct {
	UserID int64 `json:"user_id"`
}

type GetRecommendProductResp struct {
	Code     string        `json:"code"`
	Products []ProductItem `json:"products,omitempty"`
}

type ProductItem struct {
	ProductID           int64   `json:"product_id"`
	ProductName         string  `json:"product_name"`
	CategoryID          int64   `json:"category_id"`
	ProductTitle        string  `json:"product_title"`
	ProductIntro        string  `json:"product_intro"`
	ProductPicture      string  `json:"product_picture"`
	ProductPrice        float64 `json:"product_price"`
	ProductSellingPrice float64 `json:"product_selling_price"`
	ProductNum          int64   `json:"product_num"`
	ProductSales        int64   `json:"product_sales"`
	ProductIsPromotion  int     `json:"product_isPromotion"`
	ProductHot          int64   `json:"product_hot"`
}

type ProductPicture struct {
	ID             int64  `json:"id"`
	ProductID      int64  `json:"product_id"`
	ProductPicture string `json:"product_picture"`
	Intro          string `json:"intro"`
}

type SearchProductReq struct {
	Keyword string `json:"keyword"`
}

type SearchProductResp struct {
	Code     string        `json:"code"`
	Products []ProductItem `json:"products,omitempty"`
}

type SetCategoryHotZeroResp struct {
	Code string `json:"code"`
}
