// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddCollectReq struct {
	UserID    int64  `json:"user_id"`
	ProductID int64  `json:"product_id"`
	Category  string `json:"category"`
}

type AddCollectResp struct {
	Code string `json:"code"`
}

type CollectItem struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	ProductID   int64  `json:"product_id"`
	Category    string `json:"category"`
	CollectTime string `json:"collect_time"`
}

type DeleteCollectReq struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

type DeleteCollectResp struct {
	Code string `json:"code"`
}

type GetCollectReq struct {
	UserID int64 `json:"user_id"`
}

type GetCollectResp struct {
	Code     string        `json:"code"`
	Collects []CollectItem `json:"collects,omitempty"`
}
