// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddCombinationReq struct {
	MainProductID       int64   `json:"main_product_id"`
	ViceProductID       int64   `json:"vice_product_id"`
	AmountThreshold     float64 `json:"amountThreshold"`
	PriceReductionRange float64 `json:"priceReductionRange"`
}

type AddCombinationResp struct {
	Code string `json:"code"`
}

type AddProductReq struct {
	ProductName         string  `json:"product_name"`
	CategoryID          int64   `json:"category_id"`
	ProductTitle        string  `json:"product_title"`
	ProductIntro        string  `json:"product_intro"`
	ProductPicture      string  `json:"product_picture"`
	ProductPrice        float64 `json:"product_price"`
	ProductSellingPrice float64 `json:"product_selling_price"`
	ProductNum          int64   `json:"product_num"`
	ProductIsPromotion  int64   `json:"product_isPromotion"`
}

type AddProductResp struct {
	Code string `json:"code"`
}

type CarouselItem struct {
	CarouselID int64  `json:"carousel_id"`
	ImgPath    string `json:"imgPath"`
	Describes  string `json:"describes"`
}

type CombinationItem struct {
	ID                  int64   `json:"id"`
	MainProductID       int64   `json:"main_product_id"`
	ViceProductID       int64   `json:"vice_product_id"`
	AmountThreshold     float64 `json:"amountThreshold"`
	PriceReductionRange float64 `json:"priceReductionRange"`
}

type DeleteCombinationReq struct {
	ID int64 `json:"id"`
}

type DeleteCombinationResp struct {
	Code string `json:"code"`
}

type DeleteProductReq struct {
	ProductID int64 `json:"product_id"`
}

type DeleteProductResp struct {
	Code string `json:"code"`
}

type GetAllDiscountsResp struct {
	Code         string            `json:"code"`
	Combinations []CombinationItem `json:"combinations,omitempty"`
}

type GetAllOrdersResp struct {
	Code   string          `json:"code"`
	Orders []MgmtOrderItem `json:"orders,omitempty"`
}

type GetAllUsersResp struct {
	Code  string         `json:"code"`
	Users []MgmtUserItem `json:"users,omitempty"`
}

type GetCarouselResp struct {
	Code     string         `json:"code"`
	Carousel []CarouselItem `json:"carousel,omitempty"`
}

type GetOrdersByUserNameReq struct {
	UserName string `json:"userName"`
}

type GetOrdersByUserNameResp struct {
	Code   string          `json:"code"`
	Orders []MgmtOrderItem `json:"orders,omitempty"`
}

type GetProductsByCategoryNameReq struct {
	CategoryName string `json:"category_name"`
}

type GetProductsByCategoryNameResp struct {
	Code     string            `json:"code"`
	Products []MgmtProductItem `json:"products,omitempty"`
}

type MgmtOrderItem struct {
	ID           int64   `json:"id"`
	OrderID      int64   `json:"order_id"`
	UserID       int64   `json:"user_id"`
	UserName     string  `json:"userName"`
	ProductID    int64   `json:"product_id"`
	ProductName  string  `json:"productName"`
	ProductNum   int64   `json:"product_num"`
	ProductPrice float64 `json:"product_price"`
	OrderTime    string  `json:"order_time"`
}

type MgmtProductItem struct {
	ProductID           int64   `json:"product_id"`
	ProductName         string  `json:"product_name"`
	CategoryID          int64   `json:"category_id"`
	ProductTitle        string  `json:"product_title"`
	ProductPicture      string  `json:"product_picture"`
	ProductPrice        float64 `json:"product_price"`
	ProductSellingPrice float64 `json:"product_selling_price"`
	ProductNum          int64   `json:"product_num"`
	ProductSales        int64   `json:"product_sales"`
	ProductIsPromotion  int64   `json:"product_isPromotion"`
}

type MgmtUserItem struct {
	UserID      int64  `json:"user_id"`
	UserName    string `json:"userName"`
	PhoneNumber string `json:"userPhoneNumber"`
}

type UpdateProductReq struct {
	ProductID           int64   `json:"product_id"`
	ProductName         string  `json:"product_name,omitempty"`
	ProductTitle        string  `json:"product_title,omitempty"`
	ProductIntro        string  `json:"product_intro,omitempty"`
	ProductPicture      string  `json:"product_picture,omitempty"`
	ProductPrice        float64 `json:"product_price,omitempty"`
	ProductSellingPrice float64 `json:"product_selling_price,omitempty"`
	ProductNum          int64   `json:"product_num,omitempty"`
	ProductIsPromotion  int64   `json:"product_isPromotion,omitempty"`
}

type UpdateProductResp struct {
	Code string `json:"code"`
}

type SetCategoryHotZeroResp struct {
	Code string `json:"code"`
}
