// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/product/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product/getAllProduct",
				Handler: GetAllProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getAllUserRecommendProduct",
				Handler: GetAllUserRecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getCategory",
				Handler: GetCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getChargerList",
				Handler: GetChargerListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getDetails",
				Handler: GetProductDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getDetailsPicture",
				Handler: GetProductPicturesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getHotProduct",
				Handler: GetHotProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getOneUserRecommendProduct",
				Handler: GetRecommendProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getPhoneList",
				Handler: GetPhoneListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getProductByCategory",
				Handler: GetProductByCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getProductBySearch",
				Handler: GetProductBySearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getPromoProduct",
				Handler: GetPromoProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getPromotionProduct",
				Handler: GetPromotionProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/getProtectingShellList",
				Handler: GetProtectingShellListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/setCategoryHotZero",
				Handler: SetCategoryHotZeroHandler(serverCtx),
			},
		},
	)
}
