// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/collect/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/collect/addCollect",
					Handler: AddCollectHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/collect/deleteCollect",
					Handler: DeleteCollectHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/collect/getCollect",
					Handler: GetCollectHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/collect/isCollected",
					Handler: IsCollectedHandler(serverCtx),
				},
			}...,
		),
	)
}
