// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/cart/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/shoppingCart/addShoppingCart",
					Handler: AddCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/shoppingCart/deleteShoppingCart",
					Handler: DeleteCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/shoppingCart/getShoppingCart",
					Handler: GetCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/shoppingCart/isExistShoppingCart",
					Handler: IsExistCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/shoppingCart/updateShoppingCart",
					Handler: UpdateCartHandler(serverCtx),
				},
			}...,
		),
	)
}
