// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carouselFieldNames          = builder.RawFieldNames(&Carousel{})
	carouselRows                = strings.Join(carouselFieldNames, ",")
	carouselRowsExpectAutoSet   = strings.Join(stringx.Remove(carouselFieldNames, "`carousel_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carouselRowsWithPlaceHolder = strings.Join(stringx.Remove(carouselFieldNames, "`carousel_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	carouselModel interface {
		Insert(ctx context.Context, data *Carousel) (sql.Result, error)
		FindOne(ctx context.Context, carouselId int64) (*Carousel, error)
		Update(ctx context.Context, data *Carousel) error
		Delete(ctx context.Context, carouselId int64) error
	}

	defaultCarouselModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Carousel struct {
		CarouselId int64  `db:"carousel_id"`
		ImgPath    string `db:"imgPath"`
		Describes  string `db:"describes"`
	}
)

func newCarouselModel(conn sqlx.SqlConn) *defaultCarouselModel {
	return &defaultCarouselModel{
		conn:  conn,
		table: "`carousel`",
	}
}

func (m *defaultCarouselModel) Delete(ctx context.Context, carouselId int64) error {
	query := fmt.Sprintf("delete from %s where `carousel_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, carouselId)
	return err
}

func (m *defaultCarouselModel) FindOne(ctx context.Context, carouselId int64) (*Carousel, error) {
	query := fmt.Sprintf("select %s from %s where `carousel_id` = ? limit 1", carouselRows, m.table)
	var resp Carousel
	err := m.conn.QueryRowCtx(ctx, &resp, query, carouselId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarouselModel) Insert(ctx context.Context, data *Carousel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, carouselRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ImgPath, data.Describes)
	return ret, err
}

func (m *defaultCarouselModel) Update(ctx context.Context, data *Carousel) error {
	query := fmt.Sprintf("update %s set %s where `carousel_id` = ?", m.table, carouselRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ImgPath, data.Describes, data.CarouselId)
	return err
}

func (m *defaultCarouselModel) tableName() string {
	return m.table
}
