// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	combinationProductFieldNames          = builder.RawFieldNames(&CombinationProduct{})
	combinationProductRows                = strings.Join(combinationProductFieldNames, ",")
	combinationProductRowsExpectAutoSet   = strings.Join(stringx.Remove(combinationProductFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	combinationProductRowsWithPlaceHolder = strings.Join(stringx.Remove(combinationProductFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	combinationProductModel interface {
		Insert(ctx context.Context, data *CombinationProduct) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CombinationProduct, error)
		Update(ctx context.Context, data *CombinationProduct) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCombinationProductModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CombinationProduct struct {
		Id                  int64         `db:"id"`
		MainProductId       int64         `db:"main_product_id"` // 满减需要达到的金额
		ViceProductId       int64         `db:"vice_product_id"` // 满减金额
		AmountThreshold     sql.NullInt64 `db:"amountThreshold"`
		PriceReductionRange sql.NullInt64 `db:"priceReductionRange"`
	}
)

func newCombinationProductModel(conn sqlx.SqlConn) *defaultCombinationProductModel {
	return &defaultCombinationProductModel{
		conn:  conn,
		table: "`combination_product`",
	}
}

func (m *defaultCombinationProductModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCombinationProductModel) FindOne(ctx context.Context, id int64) (*CombinationProduct, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", combinationProductRows, m.table)
	var resp CombinationProduct
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCombinationProductModel) Insert(ctx context.Context, data *CombinationProduct) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, combinationProductRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MainProductId, data.ViceProductId, data.AmountThreshold, data.PriceReductionRange)
	return ret, err
}

func (m *defaultCombinationProductModel) Update(ctx context.Context, data *CombinationProduct) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, combinationProductRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MainProductId, data.ViceProductId, data.AmountThreshold, data.PriceReductionRange, data.Id)
	return err
}

func (m *defaultCombinationProductModel) tableName() string {
	return m.table
}
