// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentOrderFieldNames          = builder.RawFieldNames(&PaymentOrder{})
	paymentOrderRows                = strings.Join(paymentOrderFieldNames, ",")
	paymentOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentOrderFieldNames, "`id`"), ",")
	paymentOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentOrderFieldNames, "`id`"), "=?,") + "=?"
)

type (
	paymentOrderModel interface {
		Insert(ctx context.Context, data *PaymentOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PaymentOrder, error)
		Update(ctx context.Context, data *PaymentOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaymentOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PaymentOrder struct {
		Id             int64  `db:"id"`
		PaymentNo      string `db:"payment_no"`
		OrderId        int64  `db:"order_id"`
		UserId         int64  `db:"user_id"`
		Amount         int64  `db:"amount"`
		Channel        string `db:"channel"`
		ChannelTradeNo string `db:"channel_trade_no"`
		Status         int64  `db:"status"`
		ExpireTime     int64  `db:"expire_time"`
		PaidTime       int64  `db:"paid_time"`
		NotifyUrl      string `db:"notify_url"`
		Extra          string `db:"extra"`
		CreatedAt      int64  `db:"created_at"`
		UpdatedAt      int64  `db:"updated_at"`
	}
)

func newPaymentOrderModel(conn sqlx.SqlConn) *defaultPaymentOrderModel {
	return &defaultPaymentOrderModel{
		conn:  conn,
		table: "`payment_order`",
	}
}

func (m *defaultPaymentOrderModel) Insert(ctx context.Context, data *PaymentOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
		m.table, paymentOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query,
		data.PaymentNo, data.OrderId, data.UserId, data.Amount,
		data.Channel, data.ChannelTradeNo, data.Status, data.ExpireTime,
		data.PaidTime, data.NotifyUrl, data.Extra, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultPaymentOrderModel) FindOne(ctx context.Context, id int64) (*PaymentOrder, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentOrderRows, m.table)
	var resp PaymentOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentOrderModel) Update(ctx context.Context, data *PaymentOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query,
		data.PaymentNo, data.OrderId, data.UserId, data.Amount,
		data.Channel, data.ChannelTradeNo, data.Status, data.ExpireTime,
		data.PaidTime, data.NotifyUrl, data.Extra, data.CreatedAt, data.UpdatedAt,
		data.Id)
	return err
}

func (m *defaultPaymentOrderModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaymentOrderModel) tableName() string {
	return m.table
}
