// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentRefundFieldNames          = builder.RawFieldNames(&PaymentRefund{})
	paymentRefundRows                = strings.Join(paymentRefundFieldNames, ",")
	paymentRefundRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentRefundFieldNames, "`id`"), ",")
	paymentRefundRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentRefundFieldNames, "`id`"), "=?,") + "=?"
)

type (
	paymentRefundModel interface {
		Insert(ctx context.Context, data *PaymentRefund) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PaymentRefund, error)
		Update(ctx context.Context, data *PaymentRefund) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaymentRefundModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PaymentRefund struct {
		Id               int64  `db:"id"`
		RefundNo         string `db:"refund_no"`
		PaymentNo        string `db:"payment_no"`
		OrderId          int64  `db:"order_id"`
		UserId           int64  `db:"user_id"`
		RefundAmount     int64  `db:"refund_amount"`
		Reason           string `db:"reason"`
		Channel          string `db:"channel"`
		ChannelRefundNo  string `db:"channel_refund_no"`
		Status           int64  `db:"status"`
		CreatedAt        int64  `db:"created_at"`
		UpdatedAt        int64  `db:"updated_at"`
	}
)

func newPaymentRefundModel(conn sqlx.SqlConn) *defaultPaymentRefundModel {
	return &defaultPaymentRefundModel{
		conn:  conn,
		table: "`payment_refund`",
	}
}

func (m *defaultPaymentRefundModel) Insert(ctx context.Context, data *PaymentRefund) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
		m.table, paymentRefundRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query,
		data.RefundNo, data.PaymentNo, data.OrderId, data.UserId,
		data.RefundAmount, data.Reason, data.Channel, data.ChannelRefundNo,
		data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultPaymentRefundModel) FindOne(ctx context.Context, id int64) (*PaymentRefund, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentRefundRows, m.table)
	var resp PaymentRefund
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentRefundModel) Update(ctx context.Context, data *PaymentRefund) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentRefundRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query,
		data.RefundNo, data.PaymentNo, data.OrderId, data.UserId,
		data.RefundAmount, data.Reason, data.Channel, data.ChannelRefundNo,
		data.Status, data.CreatedAt, data.UpdatedAt,
		data.Id)
	return err
}

func (m *defaultPaymentRefundModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaymentRefundModel) tableName() string {
	return m.table
}
