// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productPictureFieldNames          = builder.RawFieldNames(&ProductPicture{})
	productPictureRows                = strings.Join(productPictureFieldNames, ",")
	productPictureRowsExpectAutoSet   = strings.Join(stringx.Remove(productPictureFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productPictureRowsWithPlaceHolder = strings.Join(stringx.Remove(productPictureFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productPictureModel interface {
		Insert(ctx context.Context, data *ProductPicture) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductPicture, error)
		Update(ctx context.Context, data *ProductPicture) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductPictureModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductPicture struct {
		Id             int64          `db:"id"`
		ProductId      int64          `db:"product_id"`
		ProductPicture sql.NullString `db:"product_picture"`
		Intro          sql.NullString `db:"intro"`
	}
)

func newProductPictureModel(conn sqlx.SqlConn) *defaultProductPictureModel {
	return &defaultProductPictureModel{
		conn:  conn,
		table: "`product_picture`",
	}
}

func (m *defaultProductPictureModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductPictureModel) FindOne(ctx context.Context, id int64) (*ProductPicture, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productPictureRows, m.table)
	var resp ProductPicture
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductPictureModel) Insert(ctx context.Context, data *ProductPicture) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, productPictureRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.ProductPicture, data.Intro)
	return ret, err
}

func (m *defaultProductPictureModel) Update(ctx context.Context, data *ProductPicture) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productPictureRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.ProductPicture, data.Intro, data.Id)
	return err
}

func (m *defaultProductPictureModel) tableName() string {
	return m.table
}
