// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productFieldNames          = builder.RawFieldNames(&Product{})
	productRows                = strings.Join(productFieldNames, ",")
	productRowsExpectAutoSet   = strings.Join(stringx.Remove(productFieldNames, "`product_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productRowsWithPlaceHolder = strings.Join(stringx.Remove(productFieldNames, "`product_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productModel interface {
		Insert(ctx context.Context, data *Product) (sql.Result, error)
		FindOne(ctx context.Context, productId int64) (*Product, error)
		Update(ctx context.Context, data *Product) error
		Delete(ctx context.Context, productId int64) error
	}

	defaultProductModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Product struct {
		ProductId           int64          `db:"product_id"`
		ProductName         string         `db:"product_name"`
		CategoryId          int64          `db:"category_id"`
		ProductTitle        string         `db:"product_title"`
		ProductIntro        string         `db:"product_intro"`
		ProductPicture      sql.NullString `db:"product_picture"`
		ProductPrice        float64        `db:"product_price"`
		ProductSellingPrice float64        `db:"product_selling_price"`
		ProductNum          int64          `db:"product_num"`
		ProductSales        sql.NullInt64  `db:"product_sales"`
		ProductIsPromotion  int64          `db:"product_isPromotion"` // 用于统计全站的促销商品，用于推荐给用户
		ProductHot          sql.NullInt64  `db:"product_hot"`         // 用于统计全站购买热度的最多的前几个商品，用于推荐给用户
	}
)

func newProductModel(conn sqlx.SqlConn) *defaultProductModel {
	return &defaultProductModel{
		conn:  conn,
		table: "`product`",
	}
}

func (m *defaultProductModel) Delete(ctx context.Context, productId int64) error {
	query := fmt.Sprintf("delete from %s where `product_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, productId)
	return err
}

func (m *defaultProductModel) FindOne(ctx context.Context, productId int64) (*Product, error) {
	query := fmt.Sprintf("select %s from %s where `product_id` = ? limit 1", productRows, m.table)
	var resp Product
	err := m.conn.QueryRowCtx(ctx, &resp, query, productId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) Insert(ctx context.Context, data *Product) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductName, data.CategoryId, data.ProductTitle, data.ProductIntro, data.ProductPicture, data.ProductPrice, data.ProductSellingPrice, data.ProductNum, data.ProductSales, data.ProductIsPromotion, data.ProductHot)
	return ret, err
}

func (m *defaultProductModel) Update(ctx context.Context, data *Product) error {
	query := fmt.Sprintf("update %s set %s where `product_id` = ?", m.table, productRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductName, data.CategoryId, data.ProductTitle, data.ProductIntro, data.ProductPicture, data.ProductPrice, data.ProductSellingPrice, data.ProductNum, data.ProductSales, data.ProductIsPromotion, data.ProductHot, data.ProductId)
	return err
}

func (m *defaultProductModel) tableName() string {
	return m.table
}
