// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seckillActivityFieldNames          = builder.RawFieldNames(&SeckillActivity{})
	seckillActivityRows                = strings.Join(seckillActivityFieldNames, ",")
	seckillActivityRowsExpectAutoSet   = strings.Join(stringx.Remove(seckillActivityFieldNames, "`id`"), ",")
	seckillActivityRowsWithPlaceHolder = strings.Join(stringx.Remove(seckillActivityFieldNames, "`id`"), "=?,") + "=?"
)

type (
	seckillActivityModel interface {
		Insert(ctx context.Context, data *SeckillActivity) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SeckillActivity, error)
		Update(ctx context.Context, data *SeckillActivity) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSeckillActivityModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeckillActivity struct {
		Id             int64  `db:"id"`
		Title          string `db:"title"`
		ProductId      int64  `db:"product_id"`
		SeckillPrice   int64  `db:"seckill_price"`
		OriginalPrice  int64  `db:"original_price"`
		TotalStock     int64  `db:"total_stock"`
		AvailableStock int64  `db:"available_stock"`
		LimitPerUser   int64  `db:"limit_per_user"`
		StartTime      int64  `db:"start_time"`
		EndTime        int64  `db:"end_time"`
		Status         int64  `db:"status"`
		CreatedAt      int64  `db:"created_at"`
		UpdatedAt      int64  `db:"updated_at"`
	}
)

func newSeckillActivityModel(conn sqlx.SqlConn) *defaultSeckillActivityModel {
	return &defaultSeckillActivityModel{
		conn:  conn,
		table: "`seckill_activity`",
	}
}

func (m *defaultSeckillActivityModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeckillActivityModel) FindOne(ctx context.Context, id int64) (*SeckillActivity, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seckillActivityRows, m.table)
	var resp SeckillActivity
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillActivityModel) Insert(ctx context.Context, data *SeckillActivity) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, seckillActivityRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.ProductId, data.SeckillPrice, data.OriginalPrice, data.TotalStock, data.AvailableStock, data.LimitPerUser, data.StartTime, data.EndTime, data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultSeckillActivityModel) Update(ctx context.Context, data *SeckillActivity) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seckillActivityRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.ProductId, data.SeckillPrice, data.OriginalPrice, data.TotalStock, data.AvailableStock, data.LimitPerUser, data.StartTime, data.EndTime, data.Status, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultSeckillActivityModel) tableName() string {
	return m.table
}
