// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seckillOrderFieldNames          = builder.RawFieldNames(&SeckillOrder{})
	seckillOrderRows                = strings.Join(seckillOrderFieldNames, ",")
	seckillOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(seckillOrderFieldNames, "`id`"), ",")
	seckillOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(seckillOrderFieldNames, "`id`"), "=?,") + "=?"
)

type (
	seckillOrderModel interface {
		Insert(ctx context.Context, data *SeckillOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SeckillOrder, error)
		Update(ctx context.Context, data *SeckillOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSeckillOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeckillOrder struct {
		Id           int64 `db:"id"`
		ActivityId   int64 `db:"activity_id"`
		OrderId      int64 `db:"order_id"`
		UserId       int64 `db:"user_id"`
		ProductId    int64 `db:"product_id"`
		SeckillPrice int64 `db:"seckill_price"`
		Num          int64 `db:"num"`
		CreatedAt    int64 `db:"created_at"`
	}
)

func newSeckillOrderModel(conn sqlx.SqlConn) *defaultSeckillOrderModel {
	return &defaultSeckillOrderModel{
		conn:  conn,
		table: "`seckill_order`",
	}
}

func (m *defaultSeckillOrderModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeckillOrderModel) FindOne(ctx context.Context, id int64) (*SeckillOrder, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seckillOrderRows, m.table)
	var resp SeckillOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeckillOrderModel) Insert(ctx context.Context, data *SeckillOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, seckillOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ActivityId, data.OrderId, data.UserId, data.ProductId, data.SeckillPrice, data.Num, data.CreatedAt)
	return ret, err
}

func (m *defaultSeckillOrderModel) Update(ctx context.Context, data *SeckillOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seckillOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ActivityId, data.OrderId, data.UserId, data.ProductId, data.SeckillPrice, data.Num, data.CreatedAt, data.Id)
	return err
}

func (m *defaultSeckillOrderModel) tableName() string {
	return m.table
}
