// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shoppingcartFieldNames          = builder.RawFieldNames(&Shoppingcart{})
	shoppingcartRows                = strings.Join(shoppingcartFieldNames, ",")
	shoppingcartRowsExpectAutoSet   = strings.Join(stringx.Remove(shoppingcartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shoppingcartRowsWithPlaceHolder = strings.Join(stringx.Remove(shoppingcartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shoppingcartModel interface {
		Insert(ctx context.Context, data *Shoppingcart) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Shoppingcart, error)
		Update(ctx context.Context, data *Shoppingcart) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShoppingcartModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Shoppingcart struct {
		Id        int64 `db:"id"`
		UserId    int64 `db:"user_id"`
		ProductId int64 `db:"product_id"`
		Num       int64 `db:"num"`
	}
)

func newShoppingcartModel(conn sqlx.SqlConn) *defaultShoppingcartModel {
	return &defaultShoppingcartModel{
		conn:  conn,
		table: "`shoppingcart`",
	}
}

func (m *defaultShoppingcartModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShoppingcartModel) FindOne(ctx context.Context, id int64) (*Shoppingcart, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shoppingcartRows, m.table)
	var resp Shoppingcart
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShoppingcartModel) Insert(ctx context.Context, data *Shoppingcart) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, shoppingcartRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ProductId, data.Num)
	return ret, err
}

func (m *defaultShoppingcartModel) Update(ctx context.Context, data *Shoppingcart) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shoppingcartRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ProductId, data.Num, data.Id)
	return err
}

func (m *defaultShoppingcartModel) tableName() string {
	return m.table
}
