// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysmanagerFieldNames          = builder.RawFieldNames(&Sysmanager{})
	sysmanagerRows                = strings.Join(sysmanagerFieldNames, ",")
	sysmanagerRowsExpectAutoSet   = strings.Join(stringx.Remove(sysmanagerFieldNames, "`sys_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysmanagerRowsWithPlaceHolder = strings.Join(stringx.Remove(sysmanagerFieldNames, "`sys_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysmanagerModel interface {
		Insert(ctx context.Context, data *Sysmanager) (sql.Result, error)
		FindOne(ctx context.Context, sysId int64) (*Sysmanager, error)
		FindOneBySysname(ctx context.Context, sysname string) (*Sysmanager, error)
		Update(ctx context.Context, data *Sysmanager) error
		Delete(ctx context.Context, sysId int64) error
	}

	defaultSysmanagerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Sysmanager struct {
		SysId           int64          `db:"sys_id"`
		Sysname         string         `db:"sysname"`
		Syspassword     string         `db:"syspassword"`
		UserPhoneNumber sql.NullString `db:"userPhoneNumber"`
	}
)

func newSysmanagerModel(conn sqlx.SqlConn) *defaultSysmanagerModel {
	return &defaultSysmanagerModel{
		conn:  conn,
		table: "`sysmanager`",
	}
}

func (m *defaultSysmanagerModel) Delete(ctx context.Context, sysId int64) error {
	query := fmt.Sprintf("delete from %s where `sys_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, sysId)
	return err
}

func (m *defaultSysmanagerModel) FindOne(ctx context.Context, sysId int64) (*Sysmanager, error) {
	query := fmt.Sprintf("select %s from %s where `sys_id` = ? limit 1", sysmanagerRows, m.table)
	var resp Sysmanager
	err := m.conn.QueryRowCtx(ctx, &resp, query, sysId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysmanagerModel) FindOneBySysname(ctx context.Context, sysname string) (*Sysmanager, error) {
	var resp Sysmanager
	query := fmt.Sprintf("select %s from %s where `sysname` = ? limit 1", sysmanagerRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, sysname)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysmanagerModel) Insert(ctx context.Context, data *Sysmanager) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sysmanagerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Sysname, data.Syspassword, data.UserPhoneNumber)
	return ret, err
}

func (m *defaultSysmanagerModel) Update(ctx context.Context, newData *Sysmanager) error {
	query := fmt.Sprintf("update %s set %s where `sys_id` = ?", m.table, sysmanagerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Sysname, newData.Syspassword, newData.UserPhoneNumber, newData.SysId)
	return err
}

func (m *defaultSysmanagerModel) tableName() string {
	return m.table
}
