// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/ErizJ/JMall/backend/service/management/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/resources/carousel",
				Handler: GetCarouselHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/management/addProduct",
					Handler: AddProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/addProductCombination",
					Handler: AddCombinationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/deleteProductCombinationById",
					Handler: DeleteCombinationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/getAllDiscounts",
					Handler: GetAllDiscountsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/getAllOrders",
					Handler: GetAllOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/getAllUsers",
					Handler: GetAllUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/getOrdersByUserName",
					Handler: GetOrdersByUserNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/getProductsByCategoryName",
					Handler: GetProductsByCategoryNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/product/deleteProductById",
					Handler: DeleteProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/product/updateProduct",
					Handler: UpdateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/management/setCategoryHotZero",
					Handler: SetCategoryHotZeroHandler(serverCtx),
				},
			}...,
		),
	)
}
